name: maternal_infant_care
description: Vatsalya - A Maternal & Infant Care Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Localization
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Notifications
  flutter_local_notifications: ^17.2.4
  
  # Charts
  fl_chart: ^0.66.0
  
  # Animations
  lottie: ^3.0.0
  
  # Utils
  intl: ^0.20.2
  path_provider: ^2.1.1
  pdf: ^3.10.7
  printing: ^5.12.0
  timezone: ^0.9.2
  shared_preferences: ^2.2.2
  
  # UI
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  sqflite: ^2.3.0
  
  # Backend & AI
  supabase_flutter: ^2.3.0
  google_generative_ai: ^0.4.0
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.7+1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.9
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icons/logo.jpeg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/translations/
